name: Unit tests
on: [push]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: info
        run: |
          echo "Triggered by ${{ github.event_name }} event"
          echo "Running on ${{ runner.os }} server"
          echo ""
          echo "Repository: ${{ github.repository }}"
          echo "Branch name: ${{ github.ref }}"
      - name: List files in the repository
        run: |
          find ${{ github.workspace }}/* | sed 's|[^/]*/|- |g'

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements_build.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 databripy --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 120 chars wide
          flake8 databripy --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      - name: Test with pytest
        run: |
          pytest